---

#
# This is the initial playbook.  I'll probably start out with one big playbook
# and then refactor into indivdual plays/tasks/etc.
#

- name: Setup a fresh Linux machine
  hosts: localhost
  gather_facts: true
  vars:
    ansible_connection: local
    packages:
      - vim
      - htop
      - atop
      - btop
      - gnome-tweaks
      - google-chrome-stable
      - ripgrep
      - fzf
      - element-desktop
      - brave-browser
      - keepass2
      - pidgin
      - lynx
      - ncdu
      - azure-cli
      - podman  # installs natively on 22.04+
      - powershell
      - solaar
    apt_repositories:
      - repo: deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe
        filename: ubuntu
      - repo: deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates universe
        filename: ubuntu
      - repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
        filename: google-chrome
      - repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main
        filename: azure-cli
      - repo: deb [signed-by=/usr/share/keyrings/element-io-archive-keyring.gpg] https://packages.element.io/debian/ default main
        filename: element-io
      - repo: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
        filename: brave-browser
      - repo: deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/ubuntu/{{ ansible_distribution_version }}/prod {{ ansible_distribution_release }} main
        filename: microsoft-prod.list
      - repo: deb http://ppa.launchpad.net/solaar-unifying/ppa/ubuntu {{ ansible_distribution_release }} main
        filename: solaar-unifying
    apt_keys:
      - url: https://packages.microsoft.com/keys/microsoft.asc
        keyring: /etc/apt/trusted.gpg.d/microsoft.asc.gpg
      - url: https://dl.google.com/linux/linux_signing_key.pub
      - url: https://packages.element.io/debian/element-io-archive-keyring.gpg
        keyring: /usr/share/keyrings/element-io-archive-keyring.gpg
      - url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        keyring: /usr/share/keyrings/brave-browser-archive-keyring.gpg
  tasks:

    - name: Enable passwordless sudo
      become: true
      ansible.builtin.copy:
        dest: /etc/sudoers.d/ben
        content: |
          ben     ALL=(ALL)   NOPASSWD: ALL
        mode: u=rw,g=r,o=r
      tags: [sudo]

    - name: APT | Ensure dependencies installed
      become: true
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - software-properties-common
        state: present
      tags: [dependencies]

    - name: APT_KEY | Add apt keys
      become: true
      ansible.builtin.apt_key:
        url: "{{ item.url }}"
        state: present
        keyring: "{{ item.keyring | default(omit) }}"
      loop: "{{ apt_keys }}"
      tags: [apt, apt_keys]

    - name: Ensure apt repositories present
      become: true
      ansible.builtin.apt_repository:
        repo: "{{ item.repo }}"
        state: "{{ item.state | default('present') }}"
        filename: "{{ item.filename | default(omit) }}"
      loop: "{{ apt_repositories }}"
      tags: [apt, apt_repository, packages]
      notify:
        - Update cache

    - name: Update cache by notifying handlers now
      ansible.builtin.meta: flush_handlers
      tags: [apt, apt_repository, packages]

    - name: Install packages
      become: true
      ansible.builtin.package:
        name: "{{ packages }}"
      tags: [apt, packages]

  handlers:

    - name: Update cache
      become: true
      ansible.builtin.apt:
        update_cache: true
